In [1]:
import pandas as pd
import pickle as pk
from sklearn.model_selection import train_test_split
from sklearn import preprocessing,metrics,ensemble

In [2]:
data = pd.read_csv("Instagram_fake_profile_dataset.csv")
data

      profile pic  nums/length username  ...  #follows  fake
0               1              0.270000  ...       955     0
1               1              0.000000  ...       533     0
2               1              0.100000  ...        98     0
3               1              0.000000  ...       651     0
4               1              0.000000  ...       126     0
...           ...                   ...  ...       ...   ...
4995            0              0.258135  ...       217     1
4996            0              0.511986  ...        24     1
4997            0              0.473108  ...         0     1
4998            0              0.293326  ...      5120     1
4999            0              0.605471  ...       344     1

[5000 rows x 12 columns]

In [3]:
data = data.drop_duplicates()
data.duplicated().sum(), data.isnull().sum()

(np.int64(0),
 profile pic             0
 nums/length username    0
 fullname words          0
 nums/length fullname    0
 name==username          0
 description length      0
 external URL            0
 private                 0
 #posts                  0
 #followers              0
 #follows                0
 fake                    0
 dtype: int64)

In [4]:
data.shape

(4934, 12)

In [5]:
x = data.drop("fake",axis=1)
y = data["fake"]
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, train_size=0.8)

In [6]:
scalar = preprocessing.StandardScaler()
x_train = pd.DataFrame((scalar.fit_transform(x_train)))
x_test = scalar.transform(x_test)

x_train.describe().T

     count          mean       std  ...       50%       75%        max
0   3947.0 -1.080126e-17  1.000127  ...  0.822197  0.822197   0.822197
1   3947.0  6.840797e-17  1.000127  ... -0.381989  0.714153   3.835924
2   3947.0  2.970346e-17  1.000127  ... -0.230025  0.929500  12.524746
3   3947.0 -7.200838e-17  1.000127  ... -0.343247 -0.343247   8.919417
4   3947.0 -6.300734e-17  1.000127  ... -0.087515 -0.087515  11.426577
5   3947.0  1.620189e-17  1.000127  ... -0.598964  0.304242   3.886955
6   3947.0  4.500524e-17  1.000127  ... -0.221127 -0.221127   4.522288
7   3947.0  6.345739e-17  1.000127  ... -0.544655 -0.544655   1.836024
8   3947.0  1.125131e-17  1.000127  ... -0.243006 -0.059685  18.415307
9   3947.0  9.001048e-19  1.000127  ... -0.088919 -0.088056  23.643980
10  3947.0 -3.150367e-18  1.000127  ... -0.315762  0.153813   9.491943

[11 rows x 8 columns]

In [7]:
model_forest = ensemble.RandomForestClassifier()
model_forest.fit(x_train,y_train)
y_predict_forest = model_forest.predict(x_test)
metrics.accuracy_score(y_test,y_predict_forest)*100

98.98682877406281

In [8]:
with open("scalar.pkl","wb") as file:
    try:
        pk.dump(scalar, file)
        print("scalar ----> successful")
    except:
        print("unsuccessful")

with open("model_forest.pkl","wb") as file:
    try:
        pk.dump(model_forest,file)
        print("model_forest ----> successful")
    except:
        print("unsuccessful")

scalar ----> successful
model_forest ----> successful